[package]
name = "ohl"
version = "1.0.3"
edition = "2024"

[[bin]]
name = "oo"
path = "src/main.rs"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
rand = "0.9.2"

